### PR TITLE
fix: only remove track from the selected playlist

### LINKED ISSUE #69: Removing track from one playlist removes it from all playlists
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14 / One UI 6

### Affected device model

Samsung Galaxy A52s

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Create new playlist
2. Add track to it that is part of the all tracks playlist
3. Select the track in the new playlist
4. Click the minus in the top bar

### Expected behavior

Track is removed from the new playlist but still part of all tracks

### Actual behavior

Track is removed from the new playlist and all tracks

### Screenshots/Screen recordings

_No response_

### Additional information

This is not related to the all tracks playlist, it removes the track from other normal playlists as well.

### PR DESCRIPTION
**Pull request by jguegel**
use playlist specific remove command

#### Type of change(s)
- [x] Bug fix
- [x] Feature / enhancement
- [x] Infrastructure / tooling (CI, build, deps, tests)
- [x] Documentation

#### What changed and why

- There was no playlist specific remove possibility

#### Tests performed

 - Tested with removing single and multiselected tracks which where in multiple playlist. 

#### Closes the following issue(s)

- Closes #69

#### Checklist
- [x] I read the [contribution guidelines](../blob/HEAD/CONTRIBUTING.md).
- [x] I manually tested my changes on device/emulator (if applicable).
- [x] I updated the "Unreleased" section in `CHANGELOG.md` (if applicable).
- [x] I have self-reviewed my pull request (no typos, formatting errors, etc.).
- [x] All checks are passing.

### CODE REVIEW

File: app/src/main/kotlin/org/fossify/musicplayer/helpers/AudioHelper.kt [hunk 1]
```diff
@@ -71,6 +71,13 @@ class AudioHelper(private val context: Context) {
         }
     }
 
+    fun removeTracksFromPlaylist(playlistId: Int, mediaStoreIds: List<Long>) {
+        if (mediaStoreIds.isEmpty()) return
+        mediaStoreIds.forEach { mediaId ->
+            context.tracksDAO.removeTrackFromPlaylist(playlistId, mediaId)
+        }
+    }
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/musicplayer/helpers/AudioHelper.kt]:
```suggestion
    fun removeTracksFromPlaylist(playlistId: Int, mediaStoreIds: List<Long>) {
        if (mediaStoreIds.isEmpty()) return
        context.tracksDAO.removeTracksFromPlaylist(playlistId, mediaStoreIds)
    }
```
